/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package I3.UI;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;

/**
 *
 * @author Abel
 */
public class HomePanel extends javax.swing.JFrame {

    /**
     * Creates new form HomePanel
     */
    int x,y;
    public HomePanel() {
        initComponents();
        x=getLocation().x;
        y=getLocation().y;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guest_p = new javax.swing.JButton();
        admin_p = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guest_p.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guest_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Tourist.jpeg"))); // NOI18N
        guest_p.setText("GUEST");
        guest_p.setToolTipText("GUEST");
        guest_p.setFocusable(false);
        guest_p.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guest_p.setMargin(new java.awt.Insets(2, 15, 15, 14));
        guest_p.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guest_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guest_pActionPerformed(evt);
            }
        });

        admin_p.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/admin.png"))); // NOI18N
        admin_p.setText("ADMIN");
        admin_p.setToolTipText("Admin");
        admin_p.setFocusable(false);
        admin_p.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin_p.setMargin(new java.awt.Insets(2, 15, 15, 14));
        admin_p.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        admin_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_pActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel1.setText("Login As");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(admin_p, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(guest_p, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guest_p)
                    .addComponent(admin_p))
                .addGap(9, 9, 9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guest_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guest_pActionPerformed
        dispose();
        GuestPanel guest=new GuestPanel();
    
        guest.setVisible(true);
    }//GEN-LAST:event_guest_pActionPerformed

    private void admin_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_pActionPerformed
            dispose();
        LoginFrame login=new LoginFrame();
            login.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_pActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
                new HomePanel().setVisible(true);
          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_p;
    private javax.swing.JButton guest_p;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
